# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Clover27's Blog
# email: $ echo Y2xvdmVyMjdjc3lAZ21haWwuY29tCg== | base64 -D
description: > # this means to ignore newlines until "baseurl:"
  My name is Shengyu Chen.
  我叫陈晟昱。
  I'm currently a graduate student studying at USC majoring in CS.
# Interested direction: Data Science, Machine Learning and Indie Game Development.
# Please e-mail me if u are hiring. (If not bothering run the command in ur shell :D)
baseurl: "" # the subpath of your site, e.g. /blog
url: "clover27.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  Clover27

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
